### ISSUE TITLE
Archive This Repo

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/clone-replace#44]
### Description

The [Yoast Duplicate Post](https://wordpress.org/plugins/duplicate-post/) does everything this plugin does and more, so it doesn't make sense to continue supporting it. Update this repo's README to provide notice of deprecation, point users at Yoast Duplicate Post as a replacement, and archive the repo.

### Acceptance Criteria

* Update the README to point users to the Yoast Duplicate Post plugin instead.
* Archive this repo, so it is still available, but it's made clear that it is not and will not be updated.

**Comment by scottnelle** [comment]
Should we also remove it from the plugin directory? It looks like that version is WAY behind the current version in github and it still receives a few downloads a day, although those could be bot clicks. https://wordpress.org/plugins/clone-replace/advanced/

**Comment by kevinfodness** [comment]
Yeah, let's. I didn't realize we actually published it to wp.org.

**Comment by scottnelle** [comment]
I've merged the PR. I'm going to leave it to @mboynes' discretion to remove it from the directory since it's his plugin and since I don't have access. Archiving this repo now (after archiving it once and unarchiving it to add this comment)!
